Added gra to rebase all downstream branches

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -284,7 +284,9 @@ BLUE_PLUS="${BLUE}+${CYAN}"
 # Tmux commands
 alias tmuxgood='echo -e "Pfx: Control-a
 ${PURPLE}META${NC}
-  ${CYAN}Pfx ${BLUE_PLUS} r${NC}: Reload tmux config
+  ${CYAN}Pfx ${BLUE_PLUS} y${NC}: Reload tmux config
+  ${CYAN}Pfx ${BLUE_PLUS} s${NC}: Save tmux windows
+  ${CYAN}Pfx ${BLUE_PLUS} r${NC}: Reload tmux windows
 ${PURPLE}WINDOWS${NC}
   ${CYAN}Pfx ${BLUE_PLUS} c${NC}: Make new window
   ${CYAN}Pfx ${BLUE_PLUS} ,${NC}: Rename window
@@ -378,6 +380,32 @@ function gdf() { # Git diff file
     done
   fi
   IFS=$IFS_ORIGINAL
+}
+
+function ggd() { # Git Go Downstream
+  branches=()
+  eval "$(git for-each-ref --shell --format='branches+=(%(refname))' refs/heads/)"
+  for BRANCH in "${branches[@]}"; do
+    BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name "$BRANCH")
+    UPSTREAM=$(git rev-parse --abbrev-ref --symbolic-full-name "$BRANCH"@{upstream})
+    CURRENT=$(git rev-parse --abbrev-ref HEAD)
+    if [ "$UPSTREAM" == "$CURRENT" ]; then
+      echo "ggd: $CURRENT --> $BRANCH"
+      git checkout "$BRANCH"
+      return 1
+    fi
+  done
+  echo "ggd: Cannot go downstream"
+  return 0
+}
+
+function gra() { # Git Rebase All
+  DO_REBASE=1
+  while [ $DO_REBASE -eq 1 ]; do
+    git rebase
+    ggd
+    DO_REBASE=$?
+  done
 }
 
 alias gsbno='git branch --list'
